export const copy = (es, en = es) => ({ es, en })
export const badge = (es, en = es) => copy(es, en)
export const p = (name, prices, meta = {}) => ({ name, ...prices, ...meta })

export const uiText = {
  menuTitle: copy('Drinks Menu', 'Drinks Menu'),
  featured:  copy('Destacado', 'Featured'),
  category:  copy('Categoría', 'Category'),
}

export const menuData = [
  {
    id: 'barril',
    nav: copy('De Barril', 'On Tap'),
    title: copy('De Barril', 'On Tap'),
    subtitle: copy('Pintas bien tiradas, espuma generosa y los clásicos de pub que no fallan.', 'Well-poured pints, generous foam and the pub classics that never disappoint.'),
    bannerItems: [
      { title: 'Guinness',     subtitle: copy('Stout cremoso de Irlanda, con notas tostadas y final persistente.', 'Creamy Irish stout with toasted notes and a lasting finish.'),     badge: badge('Irish classic'), mockup: 'pint'  },
      { title: "Murphy's Red", subtitle: copy('Ale roja suave, con dulzor de malta y muy fácil de beber.', 'Smooth red ale with malt sweetness and a very easy drink.'),              badge: badge('Popular'),      mockup: 'amber' },
      { title: 'Paulaner',     subtitle: copy('Trigo bávara de aroma a levadura y burbuja fresca.', 'Bavarian wheat beer with yeasty aroma and refreshing fizz.'),                   badge: badge('Wheat'),        mockup: 'wheat' },
    ],
    groups: [{
      id: 'draft', name: copy('Cervezas de barril', 'Draft beer'),
      columns: [{ key: 'halfPrice', label: '½ Pint' }, { key: 'pintPrice', label: 'Pint' }],
      defaultDescription: copy('Tirada en el momento, limpia y con ese punto de pub que se agradece.', 'Poured fresh, clean and with that pub character you appreciate.'),
      products: [
        p('Guinness',        { halfPrice: '3,3€', pintPrice: '6€'   }, { highlighted: true,  badge: badge('Irish classic'), description: copy('Stout cremoso de Irlanda, con notas tostadas y final persistente.', 'Creamy Irish stout with toasted notes and a lasting finish.') }),
        p("Murphy's Red",    { halfPrice: '3,3€', pintPrice: '6€'   }, { highlighted: true,  badge: badge('Popular'),       description: copy('Ale roja irlandesa, dulzor suave de malta y muy fácil de beber.', 'Irish red ale with gentle malt sweetness, very easy to drink.') }),
        p('Paulaner',        { halfPrice: '3,3€', pintPrice: '6€'   }, { highlighted: true,  badge: badge('Wheat'),         description: copy('Trigo bávara, suave y aromática, con burbuja fina y refrescante.', 'Bavarian wheat beer, soft and aromatic with fine, refreshing bubbles.') }),
        p('Amstel',          { halfPrice: '2,2€', pintPrice: '4€'   }, { description: copy('Lager fresca, ligera y sin complicaciones.', 'Fresh, light and uncomplicated lager.') }),
        p('Amstel Oro',      { halfPrice: '2,5€', pintPrice: '4€'   }, { description: copy('Lager con toque tostado y final suave y redondo.', 'Lager with a toasted touch and a smooth, rounded finish.') }),
        p('Tinto de Verano', { halfPrice: '2,5€', pintPrice: '4,5€' }, { badge: badge('Refrescante', 'Refreshing'), description: copy('Vino, limón, hielo y ese dulzor que refresca de verdad.', 'Wine, lemon, ice and the sweetness that truly refreshes.') }),
      ],
    }],
  },
  {
    id: 'tercios',
    nav: copy('Tercios', 'Bottles'),
    title: copy('Tercios', 'Bottles'),
    subtitle: copy('Botellas clásicas, craft y sidras para quien sabe lo que quiere.', 'Classic bottles, craft beers and ciders for those who know what they want.'),
    bannerItems: [
      { title: 'Lagunitas IPA',    subtitle: copy('IPA americana con cítrico intenso y amargor bien calibrado.', 'American IPA with bold citrus and well-calibrated bitterness.'), badge: badge('Craft'),                 mockup: 'bottle'       },
      { title: 'Judas',            subtitle: copy('Rubia belga de mucho carácter, especiada y con fuerza.', 'Full-character Belgian blonde, spiced and strong.'),                 badge: badge('Especial', 'Special'),   mockup: 'bottle-dark'  },
      { title: 'Magners Original', subtitle: copy('Sidra irlandesa de manzana, seca y muy refrescante.', 'Irish apple cider, dry and very refreshing.'),                          badge: badge('Cider'),                 mockup: 'bottle-amber' },
    ],
    groups: [
      { id: 'clasicas', name: copy('Clásicas', 'Classics'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Botella bien fría, sabor limpio y listo para disfrutar.', 'Well-chilled bottle, clean flavour and ready to enjoy.'), products: [
        p('Heineken',           { price: '2,8€' }, { description: copy('Lager holandesa, ligera, fresca e inconfundible.', 'Dutch lager, light, fresh and unmistakable.') }),
        p('Águila Dorada',      { price: '2,8€' }, { description: copy('Lager suave, dorada y de trago muy amable.', 'Smooth, golden lager and very easy to drink.') }),
        p('Águila Sin Filtrar', { price: '3,5€' }, { badge: badge('Sin filtrar', 'Unfiltered'), description: copy('Más sabor, más textura, ese punto sin filtrar que marca la diferencia.', 'More flavour, more texture — that unfiltered touch that makes the difference.') }),
        p('18/70',              { price: '2,8€' }, { description: copy('Lager de perfil ligero y final muy limpio.', 'Light-profile lager with a very clean finish.') }),
        p('Cruzcampo S.G.',     { price: '3€'   }, { description: copy('Fresca, sin gluten y sin renunciar al sabor.', 'Fresh, gluten-free and without compromising on flavour.') }),
        p('Sol',                { price: '3,5€' }, { description: copy('Lager mexicana clara, perfecta para el calor.', 'Clear Mexican lager, perfect for warm weather.') }),
        p('Moretti',            { price: '3,5€' }, { highlighted: true, badge: badge('Popular'), description: copy('Lager italiana de sabor limpio, seco y muy equilibrado.', 'Italian lager, clean flavour, dry and very well balanced.') }),
        p('Dos XX',             { price: '3,5€' }, { description: copy('Lager mexicana suave, cuerpo ligero y final amable.', 'Soft Mexican lager with light body and a gentle finish.') }),
      ]},
      { id: 'craft', name: copy('Craft · Especiales', 'Craft · Specials'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Más aroma, más cuerpo y más personalidad en cada trago.', 'More aroma, more body and more personality in every sip.'), products: [
        p('Lagunitas IPA', { price: '4€'   }, { highlighted: true, badge: badge('Craft'),              description: copy('IPA americana con cítrico intenso y amargor bien calibrado.', 'American IPA with bold citrus and well-calibrated bitterness.') }),
        p('Hop House',     { price: '4€'   }, { description: copy('Lager lupulada, aromática y con un frescor largo.', 'Hoppy lager, aromatic with a long, fresh finish.') }),
        p('Judas',         { price: '4,5€' }, { highlighted: true, badge: badge('Especial', 'Special'), description: copy('Rubia belga de mucho carácter, especiada y con fuerza.', 'Full-character Belgian blonde, spiced and strong.') }),
        p('Mort Subite',   { price: '4€'   }, { description: copy('Cerveza de fruta con acidez suave y un final goloso.', 'Fruit beer with soft acidity and a pleasantly sweet finish.') }),
      ]},
      { id: 'zeta', name: copy('Artesana Zeta', 'Zeta Craft'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Artesanas locales con identidad propia y perfiles limpios.', 'Local craft beers with their own identity and clean profiles.'), products: [
        p('Zeta Hell',    { price: '4€' }, { badge: badge('Local'), description: copy('Rubia artesana, limpia, ligera y muy bebible.', 'Craft blonde, clean, light and very drinkable.') }),
        p('Zeta Hop',     { price: '4€' }, { description: copy('Aromática y lupulada, con un amargor que no cansa.', 'Aromatic and hoppy, with a bitterness that never tires.') }),
        p('Zeta Trigger', { price: '4€' }, { description: copy('Artesana con más cuerpo y carácter que una lager normal.', 'Craft beer with more body and character than a regular lager.') }),
      ]},
      { id: 'saborizadas', name: copy('Saborizadas', 'Flavoured'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Frescas, cítricas o dulces para un momento más ligero.', 'Fresh, citrusy or sweet for a lighter moment.'), products: [
        p('Radler',     { price: '2,8€' }, { description: copy('Cerveza con limón, sin complicaciones y muy refrescante.', 'Beer with lemon, no fuss and very refreshing.') }),
        p('Desperados', { price: '3,5€' }, { badge: badge('Tequila'), description: copy('Cerveza con aroma a tequila y un punto dulce al final.', 'Beer with tequila aroma and a sweet note at the finish.') }),
        p('Ladrón',     { price: '3,5€' }, { description: copy('Sidra suave con fruta natural y punto dulce.', 'Soft cider with natural fruit and a sweet touch.') }),
      ]},
      { id: 'sidras', name: copy('Sidras Magners', 'Magners Ciders'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Sidras irlandesas bien frías, aromáticas y fáciles de beber.', 'Well-chilled Irish ciders, aromatic and easy to drink.'), products: [
        p('Magners Original', { price: '5,5€' }, { highlighted: true, badge: badge('Irish cider'), description: copy('Sidra irlandesa de manzana, seca y muy refrescante.', 'Irish apple cider, dry and very refreshing.') }),
        p('Magners Berry',    { price: '5,5€' }, { description: copy('Sidra con frutos rojos, golosa y aromática.', 'Cider with red berries, indulgent and aromatic.') }),
        p('Magners Pear',     { price: '5,5€' }, { description: copy('Sidra de pera, suave, floral y refrescante.', 'Pear cider, soft, floral and refreshing.') }),
      ]},
      { id: 'zero', name: copy('Sin Alcohol 0,0', 'Alcohol Free 0.0'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Todo el sabor de la cerveza, sin el alcohol.', 'All the beer flavour, none of the alcohol.'), products: [
        p('Heineken 0,0',   { price: '2,8€' }, { description: copy('Lager 0,0 limpia, fresca y muy equilibrada.', 'Clean, fresh and very balanced alcohol-free lager.') }),
        p('Amstel Oro 0,0', { price: '2,8€' }, { description: copy('Tostada 0,0 de cuerpo amable y sabor suave.', 'Alcohol-free toasted lager with a gentle body and soft flavour.') }),
        p('Guinness 0,0',   { price: '5€'   }, { highlighted: true, badge: badge('Irish 0,0'), description: copy('La crema del Guinness sin alcohol, con sus notas tostadas intactas.', 'Guinness creaminess without alcohol, roasted notes fully intact.') }),
        p('Zeta 0,0',       { price: '4€'   }, { description: copy('Artesana sin alcohol, con aroma limpio y carácter propio.', 'Alcohol-free craft beer with a clean aroma and its own character.') }),
      ]},
    ],
  },
  {
    id: 'sinalcohol',
    nav: copy('Sin Alcohol', 'Soft Drinks'),
    title: copy('Sin Alcohol', 'Soft Drinks'),
    subtitle: copy('Cafés, refrescos, zumos y mezclas frescas para cualquier momento del día.', 'Coffee, sodas, juices and fresh mixes for any time of day.'),
    bannerItems: [
      { title: 'Café con Leche',    subtitle: copy('Cremoso y caliente, el descanso perfecto en barra.', 'Creamy and warm, the perfect break at the bar.'),                      badge: badge('Café', 'Coffee'), mockup: 'coffee' },
      { title: 'Coca-Cola Zero',    subtitle: copy('La burbuja de siempre, sin azúcar y bien fría.', 'The classic fizz, sugar-free and ice cold.'),                              badge: badge('Zero'),           mockup: 'bottle-dark' },
      { title: 'Zumo de Cranberry', subtitle: copy('Ácido, frutal y con ese punto que despierta el paladar.', 'Tart, fruity and with that kick that wakes the palate.'),         badge: badge('Fresh'),          mockup: 'shot'   },
    ],
    groups: [
      { id: 'cafes', name: copy('Cafés & Infusiones', 'Coffee & Tea'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Clásico de barra, preparado al momento y sin prisa.', 'Bar classic, prepared fresh and without rush.'), products: [
        p('Café Solo',      { price: '1,6€' }, { description: copy('Espresso concentrado, directo y sin rodeos.', 'Concentrated espresso, direct and no-nonsense.') }),
        p('Café Cortado',   { price: '1,7€' }, { description: copy('Espresso con un pequeño toque de leche que lo redondea.', 'Espresso with a small touch of milk that rounds it out.') }),
        p('Café con Leche', { price: '1,8€' }, { highlighted: true, badge: badge('Clásico', 'Classic'), description: copy('Cremoso y caliente, el descanso perfecto en barra.', 'Creamy and warm, the perfect break at the bar.') }),
        p('Carajillo',      { price: '2,5€' }, { badge: badge('Tradición', 'Tradition'), description: copy('Café con licor, reconfortante y de aroma profundo.', 'Coffee with liqueur, warming and deeply aromatic.') }),
        p('Infusión',       { price: '1,6€' }, { description: copy('Aromática, suave y perfecta para bajar el ritmo.', 'Aromatic, gentle and perfect for slowing down.') }),
      ]},
      { id: 'refrescos', name: copy('Refrescos', 'Soft Drinks'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Bien frío, con gas y listo para apagar la sed.', 'Ice cold, fizzy and ready to quench your thirst.'), products: [
        p('Coca-Cola',        { price: '2,2€' }, { description: copy('El refresco más conocido, dulce y con burbuja intensa.', 'The world\'s most recognised soda, sweet with bold fizz.') }),
        p('Coca-Cola Zero',   { price: '2,2€' }, { highlighted: true, badge: badge('Zero'), description: copy('La burbuja de siempre, sin azúcar y bien fría.', 'The classic fizz, sugar-free and ice cold.') }),
        p('Fanta Naranja',    { price: '2,2€' }, { description: copy('Naranja dulce, cítrica y perfecta bien helada.', 'Sweet orange, citrusy and perfect ice cold.') }),
        p('Fanta Limón',      { price: '2,2€' }, { description: copy('Limón con burbuja fina y ese punto cítrico que refresca.', 'Lemon with fine bubbles and that citrus kick that refreshes.') }),
        p('Sprite',           { price: '2,2€' }, { description: copy('Lima-limón, burbuja viva y final seco y limpio.', 'Lime-lemon, lively fizz and a dry, clean finish.') }),
        p('Nestea',           { price: '2,5€' }, { description: copy('Té frío con dulzor suave y aroma a fruta.', 'Iced tea with gentle sweetness and fruity aroma.') }),
        p('Aquarius Limón',   { price: '2,5€' }, { description: copy('Cítrico y ligero, hidrata sin pesar.', 'Citrusy and light, hydrates without heaviness.') }),
        p('Aquarius Naranja', { price: '2,5€' }, { description: copy('Naranja suave, fresca y sin ser demasiado dulce.', 'Soft orange, fresh and not too sweet.') }),
        p('Aquarius Rojo',    { price: '2,5€' }, { description: copy('Frutas rojas, frescor ligero y punto dulce agradable.', 'Red fruits, light freshness and a pleasant sweet touch.') }),
      ]},
      { id: 'aguas', name: copy('Aguas & Sodas', 'Water & Sodas'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('La base fresca para acompañar o para combinar.', 'The fresh base to sip alongside or mix into.'), products: [
        p('Agua',         { price: '1,5€' }, { description: copy('Mineral fría, limpia y sin más.', 'Cold mineral water, clean and simple.') }),
        p('Agua con Gas', { price: '2,5€' }, { description: copy('Mineral con burbuja fina y final refrescante.', 'Mineral water with fine bubbles and a refreshing finish.') }),
        p('Soda',         { price: '2,2€' }, { description: copy('Burbuja neutra y limpia, ideal para combinar.', 'Neutral, clean fizz, ideal for mixing.') }),
        p('Ginger',       { price: '2,2€' }, { description: copy('Jengibre especiado con burbuja y un toque picante.', 'Spiced ginger soda with fizz and a peppery bite.') }),
        p('Tónica',       { price: '2,2€' }, { description: copy('Amargor elegante, burbuja seca y final muy limpio.', 'Elegant bitterness, dry fizz and a very clean finish.') }),
      ]},
      { id: 'zumos', name: copy('Zumos & Energéticos', 'Juices & Energy'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Fruta, energía o un toque ácido para cambiar el paso.', 'Fruit, energy or a tart edge to change the pace.'), products: [
        p('Zumo de Naranja',   { price: '2,8€' }, { description: copy('Naranja dulce y cítrica, fresca y sin artificios.', 'Sweet, citrusy orange — fresh and straightforward.') }),
        p('Zumo de Piña',      { price: '2,8€' }, { description: copy('Tropical, suave y con un aroma que transporta.', 'Tropical, soft and with an aroma that takes you away.') }),
        p('Zumo de Melocotón', { price: '2,8€' }, { description: copy('Denso, dulce y con ese aroma inconfundible a melocotón maduro.', 'Rich, sweet and with that unmistakable ripe peach aroma.') }),
        p('Zumo de Cranberry', { price: '2,8€' }, { highlighted: true, badge: badge('Fresh'), description: copy('Ácido, frutal y con ese punto que despierta el paladar.', 'Tart, fruity and with that kick that wakes the palate.') }),
        p('Monster',           { price: '3€'   }, { badge: badge('Energy'), description: copy('Energético intenso, bien frío y con gas.', 'Intense energy drink, ice cold and fizzy.') }),
      ]},
    ],
  },
  {
    id: 'ginebras',
    nav: copy('Ginebras', 'Gin'),
    title: copy('Ginebras', 'Gin'),
    subtitle: copy('Ginebras para copa larga, desde entradas accesibles hasta opciones premium de carácter.', 'Gins for long serves, from accessible pours to characterful premium options.'),
    bannerItems: [
      { title: "Hendrick's",        subtitle: copy('Floral, delicada y con ese perfume que la hace inconfundible.', 'Floral, delicate and with that fragrance that makes it unmistakable.'), badge: badge('Premium'),    mockup: 'gin' },
      { title: 'Roku',              subtitle: copy('Botánica japonesa de perfil elegante y muy aromático.', 'Japanese botanicals with an elegant, highly aromatic profile.'),              badge: badge('Botanical'), mockup: 'gin' },
      { title: 'Tanqueray Rangpur', subtitle: copy('Cítrica, viva y con mucho más carácter que una London dry normal.', 'Citrusy, vibrant and with far more character than a standard London dry.'), badge: badge('Citrus'), mockup: 'gin' },
    ],
    groups: [{ id: 'gin', name: copy('Ginebras', 'Gins'), columns: [{ key: 'shotPrice', label: 'Shot' }, { key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'combPrice', label: 'Comb.' }], defaultDescription: copy('En copa larga, aromática y lista para disfrutar.', 'In a long glass, aromatic and ready to enjoy.'), products: [
      p('Puerto de Indias',      { shotPrice: '2,5€', copaPrice: '6,5€', combPrice: '7,5€' }, { description: copy('Ginebra afrutada y dulce, muy amable en copa.', 'Fruity and sweet gin, very pleasant in a long glass.') }),
      p('Puerto de Indias Rosa', { shotPrice: '2,5€', copaPrice: '6,5€', combPrice: '7,5€' }, { badge: badge('Rosa', 'Pink'), description: copy('Fresas, fruta roja y un perfil suave que entra solo.', 'Strawberries, red fruit and a soft profile that goes down easy.') }),
      p('Macaronesian',          { shotPrice: '2,5€', copaPrice: '6,5€', combPrice: '7,5€' }, { description: copy('Botánica atlántica, fresca y con identidad canaria.', 'Atlantic botanicals, fresh and with a Canarian identity.') }),
      p('Tanqueray',             { shotPrice: '3€',   copaPrice: '6,5€', combPrice: '7,5€' }, { description: copy('London dry clásica, seca, limpia y sin fallo.', 'Classic London dry, crisp, clean and reliable.') }),
      p('Beefeater',             { shotPrice: '3€',   copaPrice: '7€',   combPrice: '8€'   }, { description: copy('Ginebra seca con cítricos marcados y buen equilibrio.', 'Dry gin with pronounced citrus notes and good balance.') }),
      p('Segrams',               { shotPrice: '3,5€', copaPrice: '7€',   combPrice: '8€'   }, { description: copy('Suave, con especias sutiles y un acabado muy redondo.', 'Smooth, with subtle spices and a very rounded finish.') }),
      p('Tanqueray Rangpur',     { shotPrice: '4€',   copaPrice: '8€',   combPrice: '9€'   }, { highlighted: true, badge: badge('Citrus'),    description: copy('Cítrica, viva y con mucho más carácter que una London dry normal.', 'Citrusy, vibrant and with far more character than a standard London dry.') }),
      p("Hendrick's",            { shotPrice: '4€',   copaPrice: '7,5€', combPrice: '9€'   }, { highlighted: true, badge: badge('Premium'),   description: copy('Floral, delicada y con ese perfume que la hace inconfundible.', 'Floral, delicate and with that fragrance that makes it unmistakable.') }),
      p('Roku',                  { shotPrice: '4€',   copaPrice: '8€',   combPrice: '9€'   }, { highlighted: true, badge: badge('Botanical'), description: copy('Botánica japonesa de perfil elegante y muy aromático.', 'Japanese botanicals with an elegant, highly aromatic profile.') }),
    ]}],
  },
  {
    id: 'rones',
    nav: copy('Rones', 'Rum'),
    title: copy('Rones', 'Rum'),
    subtitle: copy('Rones para combinar, para copa sola y opciones premium cuando la noche lo pide.', 'Rums for mixing, for sipping neat and premium options when the night calls for it.'),
    bannerItems: [
      { title: 'Zacapa',         subtitle: copy('Ron guatemalteco de barrica, dulce y de final interminable.', 'Barrel-aged Guatemalan rum, sweet with an endless finish.'), badge: badge('Premium'), mockup: 'rocks' },
      { title: 'Havana Club',    subtitle: copy('Ron cubano con carácter propio, ideal solo o acompañado.', 'Cuban rum with its own character, great neat or mixed.'),      badge: badge('Classic'), mockup: 'rocks' },
      { title: 'Capitán Morgan', subtitle: copy('Especiado, amable y con ese punto dulce que siempre funciona.', 'Spiced, approachable and with that sweet note that always works.'), badge: badge('Spiced'), mockup: 'rocks' },
    ],
    groups: [{ id: 'rum', name: copy('Rones', 'Rums'), columns: [{ key: 'shotPrice', label: 'Shot' }, { key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'combPrice', label: 'Comb.' }], defaultDescription: copy('Dulce, especiado o tropical: cada ron tiene su propio carácter.', 'Sweet, spiced or tropical — every rum has its own character.'), products: [
      p('Magua',          { shotPrice: '2,5€', copaPrice: '6,5€',  combPrice: '7,5€'  }, { description: copy('Ron de entrada suave, bueno solo y muy versátil para combinar.', 'Smooth entry-level rum, good neat and very versatile for mixing.') }),
      p('Malibu',         { shotPrice: '2,5€', copaPrice: '6,5€',  combPrice: '7,5€'  }, { badge: badge('Coco', 'Coconut'), description: copy('Coco, dulzor tropical y un perfil que invita a la copa.', 'Coconut, tropical sweetness and a profile that invites another glass.') }),
      p('Brugal',         { shotPrice: '3€',   copaPrice: '7,5€',  combPrice: '8€'    }, { description: copy('Ron seco con un punto de madera que le da profundidad.', 'Dry rum with an oak touch that adds depth.') }),
      p('Barceló',        { shotPrice: '3€',   copaPrice: '7,5€',  combPrice: '8€'    }, { description: copy('Ron dominicano suave, redondo y de muy buena relación calidad-precio.', 'Smooth Dominican rum, rounded and great value for money.') }),
      p('Capitán Morgan', { shotPrice: '3€',   copaPrice: '7,5€',  combPrice: '8€'    }, { highlighted: true, badge: badge('Spiced'),          description: copy('Especiado, amable y con ese punto dulce que siempre funciona.', 'Spiced, approachable and with that sweet note that always works.') }),
      p('Bacardi',        { shotPrice: '3,5€', copaPrice: '7€',    combPrice: '8€'    }, { description: copy('Ron blanco limpio, neutro y perfecto para cualquier combinado.', 'Clean white rum, neutral and perfect for any mixed drink.') }),
      p('Havana Club',    { shotPrice: '4€',   copaPrice: '8€',    combPrice: '9€'    }, { highlighted: true, badge: badge('Classic'),         description: copy('Ron cubano con carácter propio, ideal solo o acompañado.', 'Cuban rum with its own character, great neat or mixed.') }),
      p('Imperial',       { shotPrice: '4,5€', copaPrice: '9,5€',  combPrice: '10,5€' }, { badge: badge('Reserva', 'Reserve'),                 description: copy('Más cuerpo, más dulzor y un final especiado que se alarga.', 'More body, more sweetness and a spiced finish that lingers.') }),
      p('Zacapa',         { shotPrice: '7€',   copaPrice: '10€',   combPrice: '—'     }, { highlighted: true, badge: badge('Premium'),         description: copy('Ron guatemalteco de barrica, dulce y de final interminable.', 'Barrel-aged Guatemalan rum, sweet with an endless finish.') }),
    ]}],
  },
  {
    id: 'vodka',
    nav: copy('Vodka & Whisky', 'Vodka & Whisky'),
    title: copy('Vodkas & Whiskies', 'Vodka & Whisky'),
    subtitle: copy('Destilados de barra, clásicos irlandeses y single malts para quien quiere terminar bien.', 'House spirits, Irish classics and single malts for those who want to finish well.'),
    bannerItems: [
      { title: 'Jameson',     subtitle: copy('El whiskey irlandés de referencia, suave y muy de pub.', 'The benchmark Irish whiskey, smooth and unmistakably pub.'),   badge: badge('Irish'),   mockup: 'rocks' },
      { title: 'Macallan 12', subtitle: copy('Single malt de altura, con jerez y un final que se queda.', 'A remarkable single malt with sherry notes and a finish that stays.'), badge: badge('Premium'), mockup: 'rocks' },
      { title: 'Cîroc',       subtitle: copy('Vodka de uva premium, con una suavidad fuera de lo común.', 'Premium grape vodka with uncommon smoothness.'),             badge: badge('Premium'), mockup: 'shot'  },
    ],
    groups: [
      { id: 'vodkas', name: copy('Vodkas', 'Vodkas'), columns: [{ key: 'shotPrice', label: 'Shot' }, { key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'combPrice', label: 'Comb.' }], defaultDescription: copy('Perfil limpio y neutro, el mejor aliado para cualquier combinado.', 'Clean and neutral profile, the best ally for any mixed drink.'), products: [
        p('House Vodka', { shotPrice: '1,5€', copaPrice: '5€',    combPrice: '6,5€' }, { description: copy('Vodka de la casa, limpio y sin pretensiones.', 'House vodka, clean and unpretentious.') }),
        p('Smirnoff',    { shotPrice: '3€',   copaPrice: '7€',    combPrice: '7,5€' }, { description: copy('Vodka clásico de toda la vida, neutro y fiable.', 'The timeless classic vodka, neutral and reliable.') }),
        p('Absolut',     { shotPrice: '3,5€', copaPrice: '7,5€',  combPrice: '8€'   }, { description: copy('Vodka sueco con más personalidad que un vodka de entrada.', 'Swedish vodka with more personality than an entry-level pour.') }),
        p('Cîroc',       { shotPrice: '6€',   copaPrice: '11,5€', combPrice: '12€'  }, { highlighted: true, badge: badge('Premium'), description: copy('Vodka de uva premium, con una suavidad fuera de lo común.', 'Premium grape vodka with uncommon smoothness.') }),
      ]},
      { id: 'whiskies', name: copy('Whiskies', 'Whiskies'), columns: [{ key: 'shotPrice', label: 'Shot' }, { key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'combPrice', label: 'Comb.' }], defaultDescription: copy('Clásicos de barra con cuerpo amable y ese calor de final que se agradece.', 'Bar classics with an easy body and that warming finish you appreciate.'), products: [
        p('JB',            { shotPrice: '2,5€', copaPrice: '5€',   combPrice: '6,5€' }, { description: copy('Blended suave y ligero, entra bien solo o combinado.', 'Light, soft blended whisky, goes well neat or mixed.') }),
        p('Cutty Sark',    { shotPrice: '2,5€', copaPrice: '5€',   combPrice: '6,5€' }, { description: copy('Seco, suave y sin aspavientos, perfecto para combinar.', 'Dry, smooth and unpretentious, perfect for mixing.') }),
        p('Jim Beam',      { shotPrice: '2,5€', copaPrice: '5€',   combPrice: '6,5€' }, { description: copy('Bourbon americano con vainilla, roble y un punto dulce natural.', 'American bourbon with vanilla, oak and a natural sweetness.') }),
        p('Ballantines',   { shotPrice: '2,5€', copaPrice: '6€',   combPrice: '7€'   }, { description: copy('Blended redondo y sin aristas, un clásico que nunca defrauda.', 'Smooth, rounded blended — a classic that never disappoints.') }),
        p('Red Label',     { shotPrice: '2,5€', copaPrice: '6,5€', combPrice: '7,5€' }, { description: copy('Intenso y especiado, pensado para quien prefiere copa larga.', 'Bold and spiced, made for those who prefer a long glass.') }),
        p('Jameson',       { shotPrice: '3€',   copaPrice: '7€',   combPrice: '8€'   }, { highlighted: true, badge: badge('Irish'),           description: copy('El whiskey irlandés de referencia, suave y muy de pub.', 'The benchmark Irish whiskey, smooth and unmistakably pub.') }),
        p('Black Label',   { shotPrice: '3,5€', copaPrice: '8€',   combPrice: '9€'   }, { badge: badge('Reserva', 'Reserve'),                 description: copy('Blended con humo, complejidad y un final que dura.', 'Blended with smoke, complexity and a finish that lasts.') }),
        p("Jack Daniel's", { shotPrice: '3,5€', copaPrice: '8€',   combPrice: '9€'   }, { description: copy('Tennessee whiskey de vainilla dulce, madera y carácter propio.', 'Tennessee whiskey with sweet vanilla, oak and its own character.') }),
        p("Maker's Mark",  { shotPrice: '5€',   copaPrice: '8€',   combPrice: '9,5€' }, { badge: badge('Bourbon'), description: copy('Bourbon de trigo suave, dulce y con más elegancia que la media.', 'Soft wheat bourbon, sweet and more elegant than most.') }),
      ]},
      { id: 'premium-whisky', name: copy('Whiskies Premium', 'Premium Whiskies'), columns: [{ key: 'shotPrice', label: 'Shot' }, { key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'combPrice', label: 'Comb.' }], defaultDescription: copy('Single malts con carácter, complejidad y un final que merece la pena esperar.', 'Single malts with character, complexity and a finish worth waiting for.'), products: [
        p('Talisker 10',  { shotPrice: '6,5€', copaPrice: '11€', combPrice: '—' }, { badge: badge('Islay'),                   description: copy('Sal marina, pimienta y un humo elegante que lo distingue.', 'Sea salt, pepper and an elegant smokiness that sets it apart.') }),
        p('Macallan 12',  { shotPrice: '8€',   copaPrice: '14€', combPrice: '—' }, { highlighted: true, badge: badge('Premium'), description: copy('Single malt de altura, con jerez y un final que se queda.', 'A remarkable single malt with sherry notes and a finish that stays.') }),
        p('Lagavulin 16', { shotPrice: '9€',   copaPrice: '16€', combPrice: '—' }, { highlighted: true, badge: badge('Peated'),  description: copy('Turba intensa, profundidad absoluta y una persistencia fuera de serie.', 'Intense peat, absolute depth and an extraordinary persistence.') }),
        p('Glenlivet 18', { shotPrice: '9€',   copaPrice: '16€', combPrice: '—' }, { badge: badge('18 años', '18 years'),     description: copy('Dieciocho años de crianza en cada sorbo: fruta madura, miel y seda.', 'Eighteen years of ageing in every sip: ripe fruit, honey and silk.') }),
      ]},
    ],
  },
  {
    id: 'licores',
    nav: copy('Licores', 'Liqueurs'),
    title: copy('Licores', 'Liqueurs'),
    subtitle: copy('Chupitos, cremas, aperitivos y tragos de siempre para alargar la noche como se merece.', 'Shots, creams, aperitifs and timeless pours to stretch the night the right way.'),
    bannerItems: [
      { title: 'Baileys',      subtitle: copy('Crema irlandesa de whiskey, suave y perfecta para terminar.', 'Irish whiskey cream, smooth and perfect to finish on.'),      badge: badge('Irish cream'), mockup: 'shot' },
      { title: 'Aperol',       subtitle: copy('Naranja amarga, color vivo y ese punto que abre el apetito.', 'Bitter orange, vivid colour and that edge that opens the appetite.'), badge: badge('Spritz'),  mockup: 'wine' },
      { title: 'Jägermeister', subtitle: copy('56 hierbas, frío intenso y un sabor que no deja indiferente.', '56 herbs, intense cold and a flavour that leaves no one indifferent.'), badge: badge('Herbal'), mockup: 'shot' },
    ],
    groups: [
      { id: 'tequilas', name: copy('Tequilas', 'Tequilas'), columns: [{ key: 'shotPrice', label: 'Shot' }, { key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'combPrice', label: 'Comb.' }], defaultDescription: copy('Con sal y limón, con hielo o combinado: el tequila siempre está listo.', 'With salt and lime, on the rocks or mixed — tequila is always ready.'), products: [
        p('House Tequila', { shotPrice: '2,5€', copaPrice: '6€',   combPrice: '7€' }, { description: copy('Tequila de la casa, limpio y resolutivo.', 'House tequila, clean and no-nonsense.') }),
        p('Jose Cuervo',   { shotPrice: '3€',   copaPrice: '7,5€', combPrice: '8€' }, { badge: badge('Classic'), description: copy('Tequila clásico con cítrico natural y un toque especiado.', 'Classic tequila with natural citrus and a spiced edge.') }),
        p('Tequila Rosa',  { shotPrice: '2,5€', copaPrice: '4,5€', combPrice: '—'  }, { description: copy('Dulce, afrutado y muy suave para quien empieza.', 'Sweet, fruity and very smooth for those starting out.') }),
      ]},
      { id: 'cremas', name: copy('Amargos & Cremas', 'Bitters & Creams'), columns: [{ key: 'shotPrice', label: 'Shot' }, { key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'combPrice', label: 'Comb.' }], defaultDescription: copy('Licores con personalidad: cremosos, herbales o especiados.', 'Liqueurs with personality: creamy, herbal or spiced.'), products: [
        p('Baileys',      { shotPrice: '2,5€', copaPrice: '4,5€', combPrice: '—'   }, { highlighted: true, badge: badge('Irish cream'), description: copy('Crema irlandesa de whiskey, suave y perfecta para terminar.', 'Irish whiskey cream, smooth and perfect to finish on.') }),
        p('Tía María',    { shotPrice: '2,5€', copaPrice: '6€',   combPrice: '—'   }, { description: copy('Licor de café jamaicano con aroma tostado y punto dulce.', 'Jamaican coffee liqueur with a roasted aroma and sweet touch.') }),
        p('Licor 43',     { shotPrice: '2,5€', copaPrice: '6€',   combPrice: '7€'  }, { description: copy('Vainilla, cítricos y 43 ingredientes que no se notan pero se sienten.', 'Vanilla, citrus and 43 ingredients you don\'t notice but you feel.') }),
        p('Fireball',     { shotPrice: '2,5€', copaPrice: '6€',   combPrice: '7€'  }, { badge: badge('Cinnamon'), description: copy('Canela que pica, dulzor que aguanta y un final que calienta.', 'Cinnamon that bites, sweetness that holds and a finish that warms.') }),
        p('Jägermeister', { shotPrice: '2,5€', copaPrice: '6,5€', combPrice: '7,5€'}, { highlighted: true, badge: badge('Herbal'), description: copy('56 hierbas, frío intenso y un sabor que no deja indiferente.', '56 herbs, intense cold and a flavour that leaves no one indifferent.') }),
        p('Fernet',       { shotPrice: '3€',   copaPrice: '6,5€', combPrice: '7,5€'}, { description: copy('Amargo intenso, herbal y con ese final seco que limpia el paladar.', 'Intensely bitter, herbal and with that dry finish that cleanses the palate.') }),
      ]},
      { id: 'aperitivos', name: copy('Aperitivos', 'Aperitifs'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Para abrir la noche con notas herbales, cítricas y el tono justo de amargo.', 'To open the night with herbal, citrus notes and just the right amount of bitterness.'), products: [
        p('Martini Blanco', { price: '4,5€' }, { description: copy('Vermut blanco suave, floral y de entrada fácil.', 'Soft white vermouth, floral and easy to get into.') }),
        p('Martini Rojo',   { price: '4,5€' }, { description: copy('Vermut rojo, especiado, dulce y con cuerpo.', 'Red vermouth, spiced, sweet and full-bodied.') }),
        p('Aperol',         { price: '7€'   }, { highlighted: true, badge: badge('Spritz'), description: copy('Naranja amarga, color vivo y ese punto que abre el apetito.', 'Bitter orange, vivid colour and that edge that opens the appetite.') }),
      ]},
      { id: 'tradicionales', name: copy('Tradicionales', 'Traditional'), columns: [{ key: 'shotPrice', label: 'Shot' }, { key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'combPrice', label: 'Comb.' }], defaultDescription: copy('Los sabores de siempre, directos y sin pretensiones.', 'The timeless flavours, direct and unpretentious.'), products: [
        p('Cassalla',      { shotPrice: '2,5€', copaPrice: '6€',   combPrice: '7€'  }, { description: copy('Anís seco, intenso y muy aromático, de los de toda la vida.', 'Dry anise, bold and very aromatic — the real old-school kind.') }),
        p('Pacharán',      { shotPrice: '2,5€', copaPrice: '5,5€', combPrice: '7€'  }, { description: copy('Endrinas maceradas, dulzor suave y ese afrutado que lo hace único.', 'Macerated sloe berries, gentle sweetness and that fruitiness that makes it unique.') }),
        p('Terry',         { shotPrice: '2€',   copaPrice: '4,5€', combPrice: '6,5€'}, { description: copy('Brandy español clásico, cálido y de sabor noble.', 'Classic Spanish brandy, warm and with a noble flavour.') }),
        p('Hierbas',       { shotPrice: '2€',   copaPrice: '4€',   combPrice: '—'   }, { description: copy('Herbal, digestivo y con ese aroma que recuerda a los de antes.', 'Herbal, digestif-style and with that aroma that recalls the old days.') }),
        p('Vodka Colores', { shotPrice: '1,5€', copaPrice: '—',    combPrice: '—'   }, { badge: badge('Shot'), description: copy('Chupito dulce y llamativo para animar la mesa.', 'Sweet, colourful shot to liven up the table.') }),
      ]},
    ],
  },
  {
    id: 'vinos',
    nav: copy('Vinos & +', 'Wine & More'),
    title: copy('Vinos & Más', 'Wine & More'),
    subtitle: copy('Vinos por copa o botella, precios de Happy Hour y algo para picar si el estómago lo pide.', 'Wine by the glass or bottle, Happy Hour prices and a bite if your stomach asks for it.'),
    bannerItems: [
      { title: 'Tinto',      subtitle: copy('Copa sencilla y equilibrada para acompañar la noche sin fallo.', 'Simple, balanced glass to carry the night without fault.'), badge: badge('Vino', 'Wine'),   mockup: 'wine'  },
      { title: 'Happy Hour', subtitle: copy('Pintas, copas y chupitos con el precio que merece la tarde.', 'Pints, glasses and shots at the price the evening deserves.'), badge: badge('Oferta', 'Deal'), mockup: 'pint'  },
      { title: 'Pizza Plus', subtitle: copy('Caliente, rápida y perfecta para compartir sin complicaciones.', 'Hot, quick and perfect to share without any fuss.'),        badge: badge('Comida', 'Food'), mockup: 'pizza' },
    ],
    groups: [
      { id: 'wine', name: copy('Vinos', 'Wine'), columns: [{ key: 'copaPrice', label: copy('Copa', 'Glass') }, { key: 'bottlePrice', label: copy('Botella', 'Bottle') }], defaultDescription: copy('Copa sencilla y fácil de acompañar con lo que sea.', 'Simple glass that pairs easily with anything.'), products: [
        p('Blanco', { copaPrice: '3€',   bottlePrice: '13,5€' }, { description: copy('Fresco y ligero, con un final muy limpio.', 'Fresh and light, with a very clean finish.') }),
        p('Tinto',  { copaPrice: '3€',   bottlePrice: '13,5€' }, { highlighted: true, badge: badge('Clásico', 'Classic'), description: copy('Copa sencilla y equilibrada para acompañar la noche sin fallo.', 'Simple, balanced glass to carry the night without fault.') }),
        p('Rosado', { copaPrice: '3,5€', bottlePrice: '14,5€' }, { description: copy('Frutal, fresco y de lo más agradecido en buen tiempo.', 'Fruity, fresh and most appreciated in good weather.') }),
      ]},
      { id: 'happy-hour', name: copy('Happy Hour', 'Happy Hour'), layout: 'deals', columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Precio especial mientras dure.', 'Special price while it lasts.'), products: [
        p('Amstel Pinta',     { price: '3€'   }, { highlighted: true, badge: badge('Deal'), description: copy('Pinta fresca al precio que se agradece.', 'Fresh pint at a price you\'ll appreciate.') }),
        p('Amstel Oro Pinta', { price: '3€'   }, { highlighted: true, badge: badge('Deal'), description: copy('Tostada de barril con precio de Happy Hour.', 'Toasted draft lager at Happy Hour price.') }),
        p('Copa',             { price: '6€'   }, { description: copy('Copa seleccionada con precio especial por tiempo limitado.', 'Selected glass at a special price for a limited time.') }),
        p('Chupito',          { price: '1,5€' }, { description: copy('Chupito rápido para brindar cuando toca.', 'Quick shot for when it\'s time to toast.') }),
      ]},
      { id: 'food', name: copy('Comida', 'Food'), columns: [{ key: 'price', label: copy('Precio', 'Price') }], defaultDescription: copy('Algo sencillo y caliente para no quedarse con hambre.', 'Something simple and warm so no one goes hungry.'), products: [
        p('Papas',      { price: '1,5€' }, { description: copy('Snack salado y crujiente para acompañar la bebida.', 'Salty, crispy snack to go alongside your drink.') }),
        p('Pizza',      { price: '9€'   }, { description: copy('Clásica, caliente y fácil de compartir sin pensarlo.', 'Classic, hot and easy to share without overthinking it.') }),
        p('Pizza Plus', { price: '10€'  }, { highlighted: true, badge: badge('Popular'), description: copy('Caliente, rápida y perfecta para compartir sin complicaciones.', 'Hot, quick and perfect to share without any fuss.') }),
      ]},
    ],
  },
]
